### ISSUE TITLE
Sass support?

### ISSUE THREAD

**Issue by abe33** [sn4il/indent-tooltip#2]
It would be nice if you could support sass as well. Since the syntax is pretty close to Stylus I guess it wouldn't require much works.

**Comment by sn4il** [comment]
Sorry for my late reply. It's been a while since my last commit. I've just published a new package version with the tooltip enabled for SASS. But it only supports SASS2 syntax. However, it will work with SASS3/SCSS as long as you follow indentation.

Thank you for being interested in my package! :)
