### ISSUE TITLE
[proposal] Show full path

### ISSUE THREAD

**Issue by ilkome** [sn4il/indent-tooltip#4]
Hello.
Is it possible to show full path to the root element?

**Comment by sn4il** [comment]
Hello. Thank you for the proposal.

I implemented this in the new v0.3.0. Now you can toggle between showing either first parent row or full path to the root row. The hotkey is <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd>. I know it's not the most cosy hotkey but it's not meant to be used frequently anyways.

Please let me know if there are any issues.

**Comment by ilkome** [comment]
Work perfect! Thanks. ;)
