### ISSUE TITLE
[bug] Scroll doesn't work

### ISSUE THREAD

**Issue by ilkome** [sn4il/indent-tooltip#5]
Hello, again :)
Page scroll doesn't work when mouse inside a tooltip.

Mac. I used touchpad.

**Comment by sn4il** [comment]
Sorry but it looks like this can't be fixed. I'm having the very same issue on PC (Windows 10). It doesn't work neither with mouse nor with touchpad.

I'll do some research later but I guess I won't be able fix it.

**Comment by ilkome** [comment]
Maybe add option to select position of a tooltip(top, bottom).
My cursor usually just there where a tooltip right now.

**Comment by sn4il** [comment]
I fixed it in v0.3.1.

Sorry it took so long, I had exams.
